### ISSUE TITLE
Support filterPolicies

### ISSUE THREAD

**Issue by Jace25** [fivepapertigers/serverless-plugin-pubsub#21]
It seems that one is not able to use filter policys like
```
functions:
    function:
...
        events:
            - pubSub:
                topic:
                    name: 'TopicName'
                    arn: 'arn:aws:sns:eu-central-1:account:TopicName'
                queue: true
                filterPolicy:
                    pets:
                        - cats
                        - dogs  
```

Queue is generated corrently and added to topic, but no filter are set.

**Comment by Jace25** [comment]
Got it. Sorry. Should rtfm before
```
    function:
...
        events:
            - pubSub:
                topic:
                    name: 'TopicName'
                    arn: 'arn:aws:sns:eu-central-1:account:TopicName'
                    subscription:
                        FilterPolicy:
                            event_type:
                                - New.*
                queue:
                    name: 'Test-Consumer-Queue'
```
